### ISSUE TITLE
This lab does not have any of the test suites, and no learn open link. 

### ISSUE THREAD

**Issue by Lukeghenco** [learn-co-curriculum/bootstrap-example-rails-lab#3]
If you do a manual fork on github, the only branch with information is the cd/first draft branch. It also places the app nested inside of the root directory.

**Comment by onyoo** [comment]
Just a minor edit, the `rails_app` repo contains the app and tests. As Luke mentioned, the app only exists in the `cd/first_draft` branch.

**Comment by AnnJohn** [comment]
thanks @Lukeghenco and @onyoo we'll move this over to the master branch as soon as we can

**Comment by pletcher** [comment]
https://github.com/learn-co-curriculum/bootstrap-example-rails-lab/commit/e818fde31e10c9ee229421fb3880b9387630175e
