### ISSUE TITLE
Lab appears as a readme only

### ISSUE THREAD

**Issue by asherkory** [learn-co-curriculum/bootstrap-example-rails-lab#6]
This lab appears as a readme only (with no link to fork) on the Learn site:

<img width="1080" alt="screen shot 2016-05-06 at 1 47 07 pm" src="https://cloud.githubusercontent.com/assets/12358765/15081445/11f135cc-1391-11e6-92cd-19c800e2a0f4.png">

**Comment by aturkewi** [comment]
Thanks for pointing this out @shinyrachel I just changed it to a lab!
